FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install 

# RUN npm install --production && \
#     npm cache clean --force && \
#     rm -rf /root/.npm && \
#     rm -rf node_modules


COPY . .

# RUN npm run build

EXPOSE 5173

CMD [ "npm", "run", "dev", "--", "--host"]